# Generated by Django 2.2.5 on 2019-09-05 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('timestamp_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('timestamp_modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('share_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='share_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
