# Generated by Django 2.2.5 on 2019-09-05 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20190905_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='share_with',
        ),
        migrations.AddField(
            model_name='file',
            name='share_with',
            field=models.ManyToManyField(related_name='share_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
